frontend/modules/sales/models/Breakdown.php
<?php

namespace app\modules\sales\models;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use app\modules\sales\models\BreakdownColor;
use common\models\User;
use yii\db\Expression;
use Yii;

/**
 * This is the model class for table "breakdowns".
 *
 * @property string $id
 * @property string $style
 * @property string $body
 * @property string $drawsing
 * @property string $purchase_order_number
 * @property string $description
 * @property string $delivery_date
 * @property string $start_period_date
 * @property string $end_period_date
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
class Breakdown extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'breakdowns';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['style'], 'required'],
            [['id', 'description'], 'string'],
            [['delivery_date', 'start_period_date', 'end_period_date', 'created_at', 'updated_at'], 'safe'],
            [['created_by', 'updated_by'], 'integer'],
            [['style', 'body', 'drawsing', 'purchase_order_number'], 'string', 'max' => 255]
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'style' => Yii::t('app', 'Style'),
            'body' => Yii::t('app', 'Body'),
            'drawsing' => Yii::t('app', 'Drawsing'),
            'purchase_order_number' => Yii::t('app', 'Purchase Order Number'),
            'description' => Yii::t('app', 'Description'),
            'delivery_date' => Yii::t('app', 'Delivery Date'),
            'start_period_date' => Yii::t('app', 'Start Period Date'),
            'end_period_date' => Yii::t('app', 'End Period Date'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }
    
    public function getBreakdownColors()
    {
        return $this->hasMany(BreakdownColor::className(), ['breakdown_id' => 'id']);
    }
}

frontend/modules/sales/controllers/BreakdownController.php
<?php

namespace app\modules\sales\controllers;

use Yii;
use app\modules\sales\models\Breakdown;
use app\modules\sales\models\BreakdownColor;
use app\modules\sales\models\BreakdownDetail;
use app\modules\sales\models\BreakdownScale;
use app\modules\sales\models\BreakdownPpkScale;
use app\modules\sales\models\BreakdownSearch;

use alexgx\phpexcel;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BreakdownController implements the CRUD actions for Breakdown model.
 */
class BreakdownController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Breakdown models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BreakdownSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Breakdown model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Breakdown model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Breakdown();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Breakdown model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionImportDetails($id)
    {
      $model = $this->findModel($id);
      $color = New BreakdownColor();
      
      if ($color->load(Yii::$app->request->post()) && $color->save()) {
        $fileName = $color->getUploadedfilePath('excel_file');
        
        $sheet = \moonland\phpexcel\Excel::import($fileName, [
            'setFirstRecordAsKeys' => false, // if you want to set the keys of record column with first record, if it not set, the header with use the alphabet column on excel. 
            'setIndexSheetByName' => true, // set this if your excel data with multiple worksheet, the index of array will be set with the sheet name. If this not set, the index will use numeric. 
            // 'getOnlySheet' => 'sheet1', // you can set this property if you want to get the specified sheet from the excel data with multiple worksheet.
        ]);
        
        foreach ($sheet['details'] as $key => $details) {
          // initial for first column....
          if ($key > 1) {
            $breakdown_detail = New BreakdownDetail;
            $breakdown_detail->breakdown_color_id = $color->id;
            $breakdown_detail->breakdown_id = $color->breakdown_id;
            $breakdown_detail->hangtag = $details['A'];
            $breakdown_detail->unit_quantity = $details['B'];
            $breakdown_detail->ppk_code = $details['C'];
            $breakdown_detail->ppk_quantity = $details['D'];
            $breakdown_detail->allowance = $details['F'];
            $breakdown_detail->save(false);
          }
        }
        $ppk_code = '';
        foreach ($sheet['scales'] as $key => $scales) {

          if ($key > 1) {
            $scale = New BreakdownScale;
            $scale->breakdown_color_id = $color->id;
            $scale->size = $scales['A'];
            $scale->save(false);
          }
          
          foreach (range('C', 'Z') as $idx => $char) {
            if (isset($scales[$char]) == false) {
              break;
            }
            
            if ($key == 1) {
              $ppk_code[$char] = $scales[$char];
            }

            if ($key > 1)
            {
              $ppk_quantity = $scales[$char];
              $ppk = New BreakdownPpkScale;
              $ppk->breakdown_scale_id = $scale->id;
              $ppk->ppk = $ppk_code[$char];
              $ppk->scale = $ppk_quantity;
              $ppk->save(false);
            }
          }
        }
        Yii::$app->session->setFlash('success', "You're Brekadown Details has been imported !!");
        return $this->redirect(['view', 'id' => (string) $model->id]);
      }else {
        return $this->render('_form_import_details', [
          'model' => $model,
          'color' => $color,
        ]);
      }
    }
    
    public function actionExport($id)
    {
      $objPHPExcel = new \PHPExcel();
 
      $sheet=0;
        
      $objPHPExcel->setActiveSheetIndex($sheet);
      $foos = [
              ['firstname'=>'John',
              'lastname'=>'Doe'],
              ['firstname'=>'John',
              'lastname'=>'Jones'],
              ['firstname'=>'Jane',
              'lastname'=>'Doe'],
      ];
       
      $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(20);
      $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(20);

      $objPHPExcel->getActiveSheet()->setTitle('xxx')
      ->setCellValue('A1', 'Firstname')
      ->setCellValue('B1', 'Lastname');
       
      $row = 2;
                      
      foreach ($foos as $foo) {  
              
          $objPHPExcel->getActiveSheet()->setCellValue('A'.$row,$foo['firstname']); 
          $objPHPExcel->getActiveSheet()->setCellValue('B'.$row,$foo['lastname']);
          $row++ ;
      }
              
      header('Content-Type: application/vnd.ms-excel');
      $filename = "breakdowns_".date("d-m-Y-His").".xlsx";
      header('Content-Disposition: attachment;filename='.$filename .' ');
      header('Cache-Control: max-age=0');
      $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
      $objWriter->save('php://output');
    }
    
    public function actionCreateDetails($id)
    {
      $model = $this->findModel($id);
      $color = New BreakdownColor();
      
      if ($color->load(Yii::$app->request->post()) && $color->save()) {
        return $this->redirect(['view', 'id' => (string) $model->id]);
      }else if (Yii::$app->request->isAjax) {
        return $this->renderAjax('_form_details', [
          'model' => $model,
          'color' => $color,
        ]);
      }
    }
    
    public function actionDeleteDetail($id)
    {
      
      $color = BreakdownColor::findOne($id);
      $model_id = $color->breakdown_id;
      $color->delete();
      
      return $this->redirect(['view', 'id' => (string) $model_id]);
    }

    /**
     * Deletes an existing Breakdown model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Breakdown model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Breakdown the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Breakdown::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/modules/sales/views/breakdown/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\Breakdown */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="breakdown-form">
  <div class="row">

    <?php $form = ActiveForm::begin(); ?>
    
    <div class="col-md-4">
      
      <?= $form->field($model, 'style')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'body')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'drawsing')->textInput(['maxlength' => true]) ?>
      
    </div>
    
    <div class="col-md-4">
      
      <?= $form->field($model, 'purchase_order_number')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

      
    </div>


    <div class="col-md-4">

      <?= $form->field($model, 'delivery_date')->widget(DatePicker::classname(), ['options' => ['class' => 'form-control']]) ?>

      <?= $form->field($model, 'start_period_date')->widget(DatePicker::classname(), ['options' => ['class' => 'form-control']]) ?>

      <?= $form->field($model, 'end_period_date')->widget(DatePicker::classname(), ['options' => ['class' => 'form-control']]) ?>

    </div>

  </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/sales/views/breakdown/_form_details.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\Breakdown */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="color-form">
  <div class="row">

    <?php 
      $form = ActiveForm::begin([
        'options' => [
            'id' => 'form-add-details',
            'title' => 'Add Details'
        ],
        'enableClientValidation' => true,
        'enableAjaxValidation' => false,
      ]);
    ?>
    
    <div class="col-md-12">
      
      <?= $form->field($color, 'color_name')->textInput(['maxlength' => true]) ?>
      
      <?= $form->field($color, 'breakdown_id')->hiddenInput(['value'=>$model->id])->label(false); ?>
      
    </div>

  </div>

    <div class="form-group">
        <?= Html::submitButton($color->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $color->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/sales/views/breakdown/_form_import_details.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

$this->title = Yii::t('app', 'Create Detail Breakdown');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Breakdowns'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->style, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="import_details_form">
  <div class="row">
    <?php 
      $form = ActiveForm::begin([
        'options' => [
          'id' => 'form-import-details',
          'title' => 'Import Details',
          'enctype' => 'multipart/form-data',
        ],
      ]);
    ?>
    <div class="col-md-6">

      <?= $form->field($color, 'color_name')->textInput(['maxlength' => true]) ?>

      <?= $form->field($color, 'excel_file')->fileInput(); ?>

      <?= $form->field($color, 'breakdown_id')->hiddenInput(['value'=>$model->id])->label(false); ?>

    </div>
    
  </div>
    
    <div class="form-group">
        <?= Html::submitButton($color->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $color->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    
    <?php ActiveForm::end(); ?>
</div>

frontend/modules/sales/views/breakdown/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\BreakdownSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="breakdown-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'style') ?>

    <?= $form->field($model, 'body') ?>

    <?= $form->field($model, 'drawsing') ?>

    <?= $form->field($model, 'purchase_order_number') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'delivery_date') ?>

    <?php // echo $form->field($model, 'start_period_date') ?>

    <?php // echo $form->field($model, 'end_period_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/sales/views/breakdown/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\Breakdown */

$this->title = Yii::t('app', 'Create Breakdown');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Breakdowns'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breakdown-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/sales/views/breakdown/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\sales\models\BreakdownSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Breakdowns');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breakdown-index">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Breakdown'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'style',
            'body',
            'drawsing',
            'purchase_order_number',
            // 'description:ntext',
            'delivery_date',
            // 'start_period_date',
            // 'end_period_date',
            // 'created_at',
            // 'created_by',
            // 'updated_at',
            // 'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

frontend/modules/sales/views/breakdown/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\Breakdown */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Breakdown',
]) . ' ' . $model->style;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Breakdowns'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->style, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="breakdown-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/sales/views/breakdown/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\modules\sales\models\Breakdown */

$this->title = $model->style;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Breakdowns'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breakdown-view">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        
        <?= Html::button('Create Details', ['value' => Url::to(['breakdown/create-details', 'id'=>$model->id]), 'title' => 'Create Details', 'class' => 'showModalButton btn btn-success']); ?>
        
        <?= Html::a(Yii::t('app', 'Import Details'), ['import-details', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        
        <?= Html::a(Yii::t('app', 'Download'), ['export', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <div class="row">
      <div class="col-md-6">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                // 'id',
                'style',
                'body',
                'drawsing',
                'purchase_order_number',
                'description:ntext',
                'delivery_date:date',
                'start_period_date:date',
                'end_period_date:date',
                'created_at:datetime',
                ['attribute' => 'created_by', 'value' => isset($model->createdBy) ? $model->createdBy->username : null ],
                'updated_at:datetime',
                ['attribute' => 'updated_by', 'value' => isset($model->updatedBy) ? $model->updatedBy->username : null ],
            ],
        ]) ?>
      </div>
      <div class="col-md-5">
        <table class="table table-brodered table-striped">
          <tr>
            <th>No</th>
            <th>Color</th>
            <th>Action</th>
          </tr>
          <?php foreach ($model->breakdownColors as $key => $color): ?>
            <tr>
              <td><?= $key+1; ?></td>
              <td><?= $color->color_name; ?></td>
              <td>
                <?= Html::a(Yii::t('app', 'Details'), ['/sales/breakdown-detail', 'id' => $color->id], ['class' => 'btn btn-xs btn-primary']) ?>
                <?= Html::a(Yii::t('app', 'Delete'), ['delete-detail', 'id' => $color->id], [
                    'class' => 'btn btn-xs btn-danger',
                    'data' => [
                        'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                        'method' => 'post',
                    ],
                ]) ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </table>
      </div>
    </div>

</div>

<?php
yii\bootstrap\Modal::begin([
    'header' => '<span id="modalHeaderTitle"></span>',
    'headerOptions' => ['id' => 'modalHeader'],
    'id' => 'modal',
    'size' => 'modal-md',
    //keeps from closing modal with esc key or by clicking out of the modal.
    // user must click cancel or X to close
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo '<div id="modalContent"></div>';
yii\bootstrap\Modal::end();
?>